-- MySQL Script generated by MySQL Workbench
-- Tue Sep 11 21:56:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 45183228
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 45183228
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `45183228` DEFAULT CHARACTER SET utf8 ;
USE `45183228` ;

-- -----------------------------------------------------
-- Table `45183228`.`Branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `45183228`.`Branch` ;

CREATE TABLE IF NOT EXISTS `45183228`.`Branch` (
  `branchID` CHAR(4) NOT NULL,
  `name` VARCHAR(30) NULL,
  `address` VARCHAR(30) NULL,
  `phNo` CHAR(10) NULL,
  PRIMARY KEY (`branchID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `45183228`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `45183228`.`Customer` ;

CREATE TABLE IF NOT EXISTS `45183228`.`Customer` (
  `customerID` CHAR(4) NOT NULL,
  `name` VARCHAR(30) NULL,
  `address` VARCHAR(30) NULL,
  `contactNo` CHAR(10) NULL,
  `emailAdress` VARCHAR(45) NULL,
  `joinDate` DATE NULL,
  PRIMARY KEY (`customerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `45183228`.`Debit_Card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `45183228`.`Debit_Card` ;

CREATE TABLE IF NOT EXISTS `45183228`.`Debit_Card` (
  `debitCardNum` INT(6) NOT NULL,
  `expiryDate` DATE NULL,
  `CVV` INT(3) NULL,
  `PIN` INT(6) NULL,
  PRIMARY KEY (`debitCardNum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `45183228`.`Account_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `45183228`.`Account_Type` ;

CREATE TABLE IF NOT EXISTS `45183228`.`Account_Type` (
  `accountType` CHAR(4) NOT NULL,
  `name` VARCHAR(15) NULL,
  `description` VARCHAR(45) NULL,
  `interestRate` DECIMAL(3,2) NULL,
  `serviceFee` INT NULL,
  PRIMARY KEY (`accountType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `45183228`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `45183228`.`Account` ;

CREATE TABLE IF NOT EXISTS `45183228`.`Account` (
  `BSB` INT(6) NOT NULL,
  `accountNumber` INT(4) NOT NULL,
  `curBal` DECIMAL(7,2) NULL,
  `dateOpened` DATE NULL,
  `dateClosed` DATE NULL,
  `Account Type_accountType` CHAR(4) NOT NULL,
  PRIMARY KEY (`BSB`, `accountNumber`, `Account Type_accountType`),
  INDEX `fk_Account_Account Type1_idx` (`Account Type_accountType` ASC),
  CONSTRAINT `fk_Account_Account Type1`
    FOREIGN KEY (`Account Type_accountType`)
    REFERENCES `45183228`.`Account_Type` (`accountType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `45183228`.`ATM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `45183228`.`ATM` ;

CREATE TABLE IF NOT EXISTS `45183228`.`ATM` (
  `atmNo` CHAR(6) NOT NULL,
  `location` VARCHAR(25) NULL,
  `openHour` TIME(0) NULL,
  `closeHour` TIME(0) NULL,
  `cashCap` INT NULL,
  `Branch_branchID` CHAR(4) NULL,
  PRIMARY KEY (`atmNo`),
  INDEX `fk_ATM_Branch1_idx` (`Branch_branchID` ASC),
  CONSTRAINT `fk_ATM_Branch1`
    FOREIGN KEY (`Branch_branchID`)
    REFERENCES `45183228`.`Branch` (`branchID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `45183228`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `45183228`.`Department` ;

CREATE TABLE IF NOT EXISTS `45183228`.`Department` (
  `departmentID` CHAR(4) NOT NULL,
  `name` VARCHAR(30) NULL,
  `location` VARCHAR(25) NULL,
  `contactNo` CHAR(10) NULL,
  `Departmentcol` VARCHAR(45) NULL,
  PRIMARY KEY (`departmentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `45183228`.`Assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `45183228`.`Assignment` ;

CREATE TABLE IF NOT EXISTS `45183228`.`Assignment` (
  `Department_departmentID` CHAR(4) NOT NULL,
  `Branch_branchID` CHAR(4) NOT NULL,
  PRIMARY KEY (`Department_departmentID`, `Branch_branchID`),
  INDEX `fk_Assignment_Branch1_idx` (`Branch_branchID` ASC),
  CONSTRAINT `fk_Assignment_Department1`
    FOREIGN KEY (`Department_departmentID`)
    REFERENCES `45183228`.`Department` (`departmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Assignment_Branch1`
    FOREIGN KEY (`Branch_branchID`)
    REFERENCES `45183228`.`Branch` (`branchID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `45183228`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `45183228`.`Employee` ;

CREATE TABLE IF NOT EXISTS `45183228`.`Employee` (
  `employeeID` CHAR(4) NOT NULL,
  `name` VARCHAR(30) NULL,
  `address` VARCHAR(30) NULL,
  `phNo` CHAR(10) NULL,
  `position` VARCHAR(20) NULL,
  `salary` INT NULL,
  `Assignment_Department_departmentID` CHAR(4) NOT NULL,
  `Assignment_Branch_branchID` CHAR(4) NOT NULL,
  PRIMARY KEY (`employeeID`, `Assignment_Department_departmentID`, `Assignment_Branch_branchID`),
  INDEX `fk_Employee_Assignment1_idx` (`Assignment_Department_departmentID` ASC, `Assignment_Branch_branchID` ASC),
  CONSTRAINT `fk_Employee_Assignment1`
    FOREIGN KEY (`Assignment_Department_departmentID` , `Assignment_Branch_branchID`)
    REFERENCES `45183228`.`Assignment` (`Department_departmentID` , `Branch_branchID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `45183228`.`Loan_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `45183228`.`Loan_Type` ;

CREATE TABLE IF NOT EXISTS `45183228`.`Loan_Type` (
  `loanType` CHAR(4) NOT NULL,
  `name` VARCHAR(15) NULL,
  `description` VARCHAR(45) NULL,
  `term` INT NULL,
  PRIMARY KEY (`loanType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `45183228`.`Loan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `45183228`.`Loan` ;

CREATE TABLE IF NOT EXISTS `45183228`.`Loan` (
  `loanNo` CHAR(4) NOT NULL,
  `interestRate` DECIMAL(3,2) NULL,
  `loanTotal` INT NULL,
  `outstandingBal` INT NULL,
  `Loan Type_loanType` CHAR(4) NOT NULL,
  `Account_BSB` INT(6) NOT NULL,
  `Account_accountNumber` INT(4) NOT NULL,
  PRIMARY KEY (`loanNo`, `Loan Type_loanType`),
  INDEX `fk_Loan_Account1_idx` (`Account_BSB` ASC, `Account_accountNumber` ASC),
  INDEX `fk_Loan_Loan Type1_idx` (`Loan Type_loanType` ASC),
  CONSTRAINT `fk_Loan_Account1`
    FOREIGN KEY (`Account_BSB` , `Account_accountNumber`)
    REFERENCES `45183228`.`Account` (`BSB` , `accountNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Loan_Loan Type1`
    FOREIGN KEY (`Loan Type_loanType`)
    REFERENCES `45183228`.`Loan_Type` (`loanType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `45183228`.`Cash_Withdrawal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `45183228`.`Cash_Withdrawal` ;

CREATE TABLE IF NOT EXISTS `45183228`.`Cash_Withdrawal` (
  `withdrawNumber` CHAR(4) NOT NULL,
  `location` VARCHAR(25) NULL,
  `date` DATE NULL,
  `time` TIME(0) NULL,
  `amount` INT NULL,
  `ATM_atmNo` CHAR(6) NOT NULL,
  `Debit Card_debitCardNum` INT(6) NOT NULL,
  PRIMARY KEY (`withdrawNumber`, `ATM_atmNo`, `Debit Card_debitCardNum`),
  INDEX `fk_Cash Withdrawal_ATM_idx` (`ATM_atmNo` ASC),
  INDEX `fk_Cash Withdrawal_Debit Card1_idx` (`Debit Card_debitCardNum` ASC),
  CONSTRAINT `fk_Cash Withdrawal_ATM`
    FOREIGN KEY (`ATM_atmNo`)
    REFERENCES `45183228`.`ATM` (`atmNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cash Withdrawal_Debit Card1`
    FOREIGN KEY (`Debit Card_debitCardNum`)
    REFERENCES `45183228`.`Debit_Card` (`debitCardNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `45183228`.`Loan_Repayment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `45183228`.`Loan_Repayment` ;

CREATE TABLE IF NOT EXISTS `45183228`.`Loan_Repayment` (
  `repayNumber` CHAR(4) NOT NULL,
  `desc` VARCHAR(45) NULL,
  `amount` INT NULL,
  `date` DATE NULL,
  `time` TIME(0) NULL,
  `Loan_loanNo` CHAR(4) NOT NULL,
  `Employee_employeeID` CHAR(4) NOT NULL,
  `Employee_Assignment_Department_departmentID` CHAR(4) NOT NULL,
  `Employee_Assignment_Branch_branchID` CHAR(4) NOT NULL,
  PRIMARY KEY (`repayNumber`, `Loan_loanNo`, `Employee_employeeID`, `Employee_Assignment_Department_departmentID`, `Employee_Assignment_Branch_branchID`),
  INDEX `fk_Loan Repayment_Loan1_idx` (`Loan_loanNo` ASC),
  INDEX `fk_Loan Repayment_Employee1_idx` (`Employee_employeeID` ASC, `Employee_Assignment_Department_departmentID` ASC, `Employee_Assignment_Branch_branchID` ASC),
  CONSTRAINT `fk_Loan Repayment_Loan1`
    FOREIGN KEY (`Loan_loanNo`)
    REFERENCES `45183228`.`Loan` (`loanNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Loan Repayment_Employee1`
    FOREIGN KEY (`Employee_employeeID` , `Employee_Assignment_Department_departmentID` , `Employee_Assignment_Branch_branchID`)
    REFERENCES `45183228`.`Employee` (`employeeID` , `Assignment_Department_departmentID` , `Assignment_Branch_branchID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `45183228`.`Customer_Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `45183228`.`Customer_Account` ;

CREATE TABLE IF NOT EXISTS `45183228`.`Customer_Account` (
  `Customer_customerID` CHAR(4) NOT NULL,
  `Account_BSB` INT(6) NOT NULL,
  `Account_accountNumber` INT(4) NOT NULL,
  `Debit Card_debitCardNum` INT(6) NOT NULL,
  PRIMARY KEY (`Customer_customerID`, `Account_BSB`, `Account_accountNumber`),
  INDEX `fk_Customer Account_Customer1_idx` (`Customer_customerID` ASC),
  INDEX `fk_Customer Account_Account1_idx` (`Account_BSB` ASC, `Account_accountNumber` ASC),
  INDEX `fk_Customer Account_Debit Card1_idx` (`Debit Card_debitCardNum` ASC),
  CONSTRAINT `fk_Customer Account_Customer1`
    FOREIGN KEY (`Customer_customerID`)
    REFERENCES `45183228`.`Customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer Account_Account1`
    FOREIGN KEY (`Account_BSB` , `Account_accountNumber`)
    REFERENCES `45183228`.`Account` (`BSB` , `accountNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer Account_Debit Card1`
    FOREIGN KEY (`Debit Card_debitCardNum`)
    REFERENCES `45183228`.`Debit_Card` (`debitCardNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `45183228`.`Manage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `45183228`.`Manage` ;

CREATE TABLE IF NOT EXISTS `45183228`.`Manage` (
  `Employee_employeeID` CHAR(4) NOT NULL,
  `Branch_branchID` CHAR(4) NOT NULL,
  `Department_departmentID` CHAR(4) NOT NULL,
  `startDate` INT NULL,
  `endDate` VARCHAR(45) NULL,
  PRIMARY KEY (`Employee_employeeID`, `Branch_branchID`, `Department_departmentID`),
  INDEX `fk_Manage_Branch1_idx` (`Branch_branchID` ASC),
  INDEX `fk_Manage_Department1_idx` (`Department_departmentID` ASC),
  CONSTRAINT `fk_Manage_Employee1`
    FOREIGN KEY (`Employee_employeeID`)
    REFERENCES `45183228`.`Employee` (`employeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Manage_Branch1`
    FOREIGN KEY (`Branch_branchID`)
    REFERENCES `45183228`.`Branch` (`branchID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Manage_Department1`
    FOREIGN KEY (`Department_departmentID`)
    REFERENCES `45183228`.`Department` (`departmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
